# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('level', models.IntegerField(help_text='Codes of 1 to 4 for different user types', null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_super_level', models.BooleanField(default=False)),
                ('id_number', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('reference_number', models.CharField(max_length=100, null=True)),
                ('registration_number', models.CharField(help_text='Of the business', max_length=200, null=True)),
                ('physical_address', models.CharField(max_length=200, null=True)),
                ('secret_key', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'db_table': 'users',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
