# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(null=True, upload_to='users/profile_photos/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
