# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
