# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_national_id_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='certificate',
            new_name='bank_guarantee_certificate',
        ),
        migrations.AddField(
            model_name='user',
            name='business_certificate',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='kra_pin_certificate',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
