# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161202_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_guarantee_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kra_pin_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id_photo',
        ),
    ]
