# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20161203_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100, unique=True)),
                ('is_email', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_time_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
