# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_contactconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactconfirmation',
            name='date_time_processed',
            field=models.DateTimeField(null=True),
        ),
    ]
