# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20161203_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactconfirmation',
            name='date_time_processed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
