# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20161203_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactconfirmation',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContactConfirmation',
        ),
    ]
