# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20161203_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=4, help_text='Codes of 1 to 4 for different user types'),
        ),
    ]
