# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_resetpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kra_pin_certificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_number',
        ),
    ]
