# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verified',
            new_name='is_email_verified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number_verified',
            new_name='is_password_changed',
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
