# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
