# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id_photo',
            field=models.ImageField(null=True, upload_to='national_id_photos/%Y/%m/%d/'),
        ),
    ]
